version: '3.8'

services:
  service-db:
    container_name: databaseForDiplom
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA="/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres-data: