server:
  port: 8080
spring:
  application:
    name: stocktaking
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://service-db:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true